name: Publish

on:
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
          registry-url: https://registry.npmjs.org/
      - run: |
          yarn
          yarn bootstrap
          yarn build
          cd packages/chain-registry
          yarn codegen
          yarn build
          cd ../../
          cd packages/assets
          yarn codegen
          cd ../../
          cd packages/osmosis
          yarn codegen
          cd ../../
          cd packages/juno
          yarn codegen
          cd ../../
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          BRANCH_NAME="build-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $BRANCH_NAME
          git add .
          git commit -am "build ðŸ› "
          git push origin $BRANCH_NAME
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_SECRET}}
          GH_TOKEN: ${{ secrets.GH_LERNA_PUBLISH_TOKEN }}
