name: Run Registry Tests ğŸ§ª

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository ğŸ“¥
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'  # Ensures submodules are also checked out

      - name: Setup Node.js ğŸŒ
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Update Git Submodules ğŸ”„
        run: |
          make update-fixtures

      - name: Install Dependencies ğŸ§¶
        run: |
          yarn install
          yarn symlink

      - name: Build Project ğŸ—ï¸
        run: |
          yarn build
          yarn symlink

      - name: Test @chain-registry/keplr ğŸ”
        run: cd packages/keplr && yarn test
      
      - name: Legacy Test @chain-registry/cosmostation ğŸ”
        run: cd legacy/cosmostation && yarn test
      
      - name: Test @chain-registry/v2-cosmostation ğŸ”
        run: cd v2/cosmostation && yarn test
      
      - name: Legacy Test @chain-registry/utils ğŸ”
        run: cd legacy/utils && yarn test
      
      - name: Test @chain-registry/utils ğŸ”
        run: cd v2/utils && yarn test
      
      - name: Legacy Test @chain-registry/client ğŸ”
        run: cd legacy/client && yarn test
        
      - name: Test @chain-registry/client ğŸ”
        run: cd v2/client && yarn test
        
      - name: Test @chain-registry/workflows ğŸ”
        run: cd workflows/workflows && yarn test

      - name: Test @chain-registry/cli ğŸ”
        run: cd workflows/cli && yarn test
