name: Run Registry Tests ğŸ§ª

on:
  pull_request:
    types: [opened, push, reopened]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository ğŸ“¥
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'  # Ensures submodules are also checked out

      - name: Setup Node.js ğŸŒ
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Update Git Submodules ğŸ”„
        run: |
          git submodule update --remote
          cd packages/chain-registry/chain-registry
          git fetch
          git checkout 5b5b73004a1acf84ed65694121828ddb6cb34de4

      - name: Install Dependencies ğŸ§¶
        run: |
          yarn install
          yarn symlink

      - name: Build Project ğŸ—ï¸
        run: yarn build

      - name: Test @chain-registry/keplr ğŸ”
        run: cd packages/keplr && yarn test
      
      - name: Test @chain-registry/cosmostation ğŸ”
        run: cd packages/cosmostation && yarn test
      
      - name: Test @chain-registry/utils ğŸ”
        run: cd packages/utils && yarn test
      
      - name: Test @chain-registry/client ğŸ”
        run: cd packages/client && yarn test
        
      - name: Test @chain-registry/workflows ğŸ”
        run: cd workflows/workflows && yarn test

      - name: Test @chain-registry/cli ğŸ”
        run: cd workflows/cli && yarn test
