name: Run Registry Tests ğŸ§ª

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository ğŸ“¥
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'  # Ensures submodules are also checked out

      - name: Setup Node.js ğŸŒ
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Update Git Submodules ğŸ”„
        run: |
          make update-fixtures

          # Enter repos/chain-registry, log commits, and pop back
          pushd repos/chain-registry
          echo "Last 2 commits in repos/chain-registry:"
          git log -n 2 --oneline
          popd

          # Enter repos/chain-registry-fixtures, log commits, and pop back
          pushd repos/chain-registry-fixtures
          echo "Last 2 commits in repos/chain-registry-fixtures:"
          git log -n 2 --oneline
          popd

      - name: Install and Build v1 ğŸ—ï¸
        run: |
          cd v1
          yarn install
          yarn symlink
          yarn build
          yarn symlink

      - name: Install and Build v2 ğŸ—ï¸
        run: |
          cd v2
          yarn install
          yarn symlink
          yarn build
          yarn symlink

      - name: Test @chain-registry/keplr ğŸ”
        run: cd v1/packages/keplr && yarn test
      
      - name: Legacy Test @chain-registry/cosmostation ğŸ”
        run: cd v1/packages/cosmostation && yarn test
      
      - name: Test @chain-registry/v2-cosmostation ğŸ”
        run: cd v2/packages/cosmostation && yarn test
      
      - name: Legacy Test @chain-registry/utils ğŸ”
        run: cd v1/packages/utils && yarn test
      
      - name: Test @chain-registry/utils ğŸ”
        run: cd v2/packages/utils && yarn test
      
      - name: Legacy Test @chain-registry/client ğŸ”
        run: cd v1/packages/client && yarn test
        
      - name: Test @chain-registry/client ğŸ”
        run: cd v2/packages/client && yarn test
        
      - name: Test @chain-registry/workflows ğŸ”
        run: cd v2/workflows/workflows && yarn test

      - name: Test @chain-registry/cli ğŸ”
        run: cd v2/workflows/cli && yarn test